# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
filter = { only_tables = ["conditions", "conditions_default"] }

[migrations_directory]
dir = "/home/user0/workspace/rust/axum-benchmark-database/migrations"
